# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:41
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_video_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
