# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20171008_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-video_at', '-id']},
        ),
    ]
