# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20170921_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
