# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_auto_20171201_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
