FROM ubuntu:18.04

MAINTAINER Zunik <chazunik@gmail.com>

RUN apt-get update && apt-get install -y git python3 python3-pip npm libmysqlclient-dev

RUN mkdir /root/.ssh/

ADD id_rsa /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN git clone git@github.com:zunik/zunik_home.git

WORKDIR /zunik_home

RUN git checkout dockerize

WORKDIR /zunik_home/app

ARG SECRET_KEY
ARG DEBUG
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG SITE_DOMAIN
ARG ALLOWED_HOSTS
ARG DISQUS_WEBSITE_SHORTNAME

ENV SECRET_KEY=${SECRET_KEY} \
    DEBUG=${DEBUG} \
    DB_HOST=${DB_HOST} \
    DB_NAME=${DB_NAME} \
    DB_USER=${DB_USER} \
    DB_PASSWORD=${DB_PASSWORD} \
    SITE_DOMAIN=${SITE_DOMAIN} \
    ALLOWED_HOSTS=${ALLOWED_HOSTS} \
    DISQUS_WEBSITE_SHORTNAME=${DISQUS_WEBSITE_SHORTNAME}

RUN pip3 install -r requirements.txt
RUN npm install -g bower && npm install
RUN python3 manage.py bower_install --allow-root

ENTRYPOINT ["gunicorn", "--bind", "0.0.0.0:8000", "zunik_home.wsgi:application"]