# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('diary_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hide', models.BooleanField(default=False)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-diary_at'],
            },
        ),
    ]
