# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-diary_at', '-id']},
        ),
    ]
