# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20171125_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='description',
            field=models.CharField(default='간략한 내용', max_length=255),
        ),
    ]
