# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20170924_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image_at',
            new_name='photo_at',
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='photo/thumbs'),
        ),
    ]
