# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 03:19
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_remove_photo_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-photo_at', '-id']},
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
