# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_otherphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
