apiVersion: v1
metadata:
  name: db-cnf
  namespace: zunik-me
kind: ConfigMap
data:
  docker.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mariadb.cnf: |-
    [client]
    default-character-set = utf8

    [mysqld]
    character-set-server  = utf8
    collation-server      = utf8_general_ci
    character_set_server   = utf8
    collation_server       = utf8_general_ci
    !includedir /etc/mysql/mariadb.conf.d/
  mysqld_safe_syslog.cnf: |-
    [mysqld_safe]
    skip_log_error
    syslog
