apiVersion: v1
metadata:
  name: db-cnf
  namespace: zunik-me
kind: ConfigMap
data:
  docker.cnf: |-
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mariadb.cnf: |-
    [client]
    default-character-set = utf8

    [mysqld]
    character-set-server  = utf8
    collation-server      = utf8_general_ci
    character_set_server   = utf8
    collation_server       = utf8_general_ci
    !includedir /etc/mysql/mariadb.conf.d/
  mysqld_safe_syslog.cnf: |-
    [mysqld_safe]
    skip_log_error
    syslog

---

kind: Pod
apiVersion: v1
metadata:
  name: db
  namespace: zunik-me
  labels:
    app: db
spec:
  containers:
    - name: db
      image: "mariadb:10.2"
      ports:
        - containerPort: 3306
      env:
        - name: TZ
          value: "Asia/Seoul"
        - name: MYSQL_DATABASE
          value: "zunik_story"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: password
      volumeMounts:
      - mountPath: "/var/lib/mysql"
        name: datadir
      - mountPath: "/etc/mysql/conf.d"
        name: dbcnf
  volumes:
    - name: datadir
      persistentVolumeClaim:
        claimName: db
    - name: dbcnf
      configMap:
        name: db-cnf
  nodeSelector:
    kubernetes.io/hostname: pool-d4b8knhi3-0ybi

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: zunik-me
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: db