apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: zunik-me
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage