apiVersion: v1
metadata:
  name: nginx-cnf
  namespace: zunik-me
kind: ConfigMap
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        client_max_body_size 100M;

        server {
            listen 80 default_server;
            charset utf-8;
            server_name localhost;

            access_log /dev/stdout;
            error_log /dev/stdout info;

            location /media/ {
                alias /var/www/media/;
            }

            location /static/ {
                alias /var/www/static/;
            }

            location / {
                proxy_pass http://localhost:8000;
                proxy_set_header    Host $host;
                proxy_set_header    X-Real-IP $remote_addr;
                proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Host $server_name;
            }
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: zunik-me
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: "nginx:1.15"
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Asia/Seoul"
          volumeMounts:
            - mountPath: "/etc/nginx/nginx.conf"
              name: nginxcnf
              subPath: nginx.conf
            - mountPath: "/var/www/media"
              name: staticfiles
              subPath: media
            - mountPath: "/var/www/static"
              name: staticfiles
              subPath: staticfiles
        - name: web
          image: "chazunik/zunik_home_web:dev4"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/zunik_home/media"
              name: staticfiles
              subPath: media
            - mountPath: "/zunik_home/staticfiles"
              name: staticfiles
              subPath: staticfiles
      imagePullSecrets:
        - name: hub-docker.default
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: zunik-me-staticfile
        - name: nginxcnf
          configMap:
            name: nginx-cnf
      nodeSelector:
        kubernetes.io/hostname: pool-d4b8knhi3-0ybi

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: zunik-me
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: web
