apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: zunik-me
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
  selector:
    app: web
  type: ClusterIP