apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: zunik-me
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "chazunik/zunik_home_web:dev2"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/zunik_home/media"
              name: staticfiles
              subPath: media
            - mountPath: "/zunik_home/staticfiles"
              name: staticfiles
              subPath: staticfiles
      imagePullSecrets:
        - name: hub-docker.default
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: zunik-me-staticfile
