# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20171126_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(height_field='height_field', upload_to=photo.models.file_rename, width_field='width_field'),
        ),
    ]
