# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import photo.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20171127_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(height_field='height_field', upload_to=photo.models.file_rename_other, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
